server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /k8s/ {
        proxy_pass http://host.docker.internal:8002/;
        proxy_set_header Host localhost;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
