server {
    listen 80;
    resolver 127.0.0.11 valid=30s ipv6=off;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires 0;
    }

    location /k8s/ {
        proxy_pass http://host.docker.internal:8002/;
        proxy_set_header Host localhost;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        set $backend http://k8s-backend:3000;
        proxy_pass $backend;
        proxy_set_header Host $host;
    }
}
